apiVersion: v1
kind: Service
metadata:
  name: runvote-service

spec:
  selector:
    app: runvote-main-jvm
  ports:
    - protocol: TCP
      port: 8989
      name: main
      targetPort: http-bapp-svc
    - protocol: UDP
      port: 8989
      targetPort: http-bapp-svc
  type: NodePort